### PR TITLE
Update BO SD excdata

### PR DESCRIPTION
**Pull request by xresende**
hysteresis
difference

### CODE REVIEW

**Review by murilobalves — APPROVED** [review]

**Review by anacso17 — APPROVED** [review]

**Review by fernandohds564 — APPROVED** [review]

**Review by LucasIB — APPROVED** [review]
graph
Direct comparison with the integrated normal sextupole from 3 excitation curves after 40 cycles of smoothed triangular curve at 2 Hz.

**Review by LuanaVilela — APPROVED** [review]

**Comment by xresende** [comment]
@fernandohds564 , @anacso17 , @murilobalves,

should we drop this set of excdata atualization PRs based on re-measurements or merge them ? we should try to decide on this ando not keep it indefinitely. In my opinion we could merge.

**Comment by anacso17** [comment]
> @fernandohds564 , @anacso17 , @murilobalves,
> 
> should we drop this set of excdata atualization PRs based on re-measurements or merge them ? we should try to decide on this ando not keep it indefinitely. In my opinion we could merge.

@xresende I think we were waiting for the BO CV excdata to complete this update, and maybe BO QS (trying to remember...). This change depends also on a script that I was working on to make the migration of all BO ramp configurations accordingly

**Comment by fernandohds564** [comment]
I think we could check what is missing and try to merge these PRs. It's been too long with them open.

**Pull request closed without merging**
