### PR TITLE
Add WIG180 feedforward correctors tables

### PR DESCRIPTION
**Pull request by xresende**

### CODE REVIEW

**Review by Gabrielrezende-asc — APPROVED** [review]

**Comment by murilobalves** [comment]
image

Data: dots, lines: interpolation curves

**Review by fernandohds564 — APPROVED** [review]

**Comment by xresende** [comment]
@anacso17 , can we merge this PR so that "excdata" of WIG180 is inserted? later we refactor how we deal with ID corrector tables. But it is useful for this table to be in the master code.

**Comment by anacso17** [comment]
> @anacso17 , can we merge this PR so that "excdata" of WIG180 is inserted? later we refactor how we deal with ID corrector tables. But it is useful for this table to be in the master code.

@xresende can we merge this one?

**Comment by fernandohds564** [comment]
If everybody agreed, why didn't we merge this one @xresende ?

**Comment by anacso17** [comment]
> If everybody agreed, why didn't we merge this one @xresende ?

@fernandohds564 , @xresende, with this PR https://github.com/lnls-sirius/dev-packages/pull/901, feefforward tables will be configurations, not tables anymore. So I think the tables here must be converted in configurations.

**Review by anacso17 — CHANGES_REQUESTED** [review]
@fernandohds564 , @xresende, with this PR https://github.com/lnls-sirius/dev-packages/pull/901, feedforward tables will be configurations, not tables anymore. So the tables here should be converted in configurations, shouldn't it?

**Comment by xresende** [comment]
> @fernandohds564 , @xresende, with this PR [lnls-sirius/dev-packages#901](https://github.com/lnls-sirius/dev-packages/pull/901), feedforward tables will be configurations, not tables anymore. So the tables here should be converted in configurations, shouldn't it?

yes, @anacso17. there is a si_idff configdb for it already. closing this PR...

**Pull request closed without merging**
