### PR TITLE
Updates on power supplies model mapping and excitation data for pulsed magnets

### PR DESCRIPTION
**Pull request by gabrielbrunheira**
Fast correctors were named as FBP-FOFB, although they won't be provided by ELP (thus it doesn't correspond to any ps_model). TB-Fam:PS-B was named as Commercial, because it'll be an off-the-shelf solution to be determined.

### CODE REVIEW

**Comment by xresende** [comment]
@lerwys , well pointed! I was the one who edited <code>beaglebone-mapping.txt</code>, not @gabrielbrunheira. I edited this file - adding fake BBBs - in order to test the integration of FAC's high-level conversion IOC with the IOC that the CON group wrote for pulsed magnet power supplies. These fake BBB names in the file might break high-level timing IOC... (@fernandohds564 ?)

I used the old scheme for naming BBBs because the slots at the naming service have not been updated according to the new scheme yet. Who will be responsible for updating it ? Daniel Tavares?

**Comment by fernandohds564** [comment]
@xresende, adding new BBBs do not break the High-level timing IOC, but changing the power supply mapping of an existing one does break it.

**Comment by xresende** [comment]
PR was closed by mistake...

**Comment by fernandohds564** [comment]
Hi @xresende, @danielot and @gabrielbrunheira.

I talked to @lerwys off line and asked him to approve this one.
We will address the issue of the definitive naming of the Beaglebones in another PR, ok?

**Pull request merged**
