### PR TITLE
Update PS test values

### PR DESCRIPTION
**Pull request by anacso17**

### CODE REVIEW

**Review by murilobalves — APPROVED** [review]

**Review by fernandohds564 — APPROVED** [review]

**Comment by xresende** [comment]
@anacso17 , maybe we should write down a comment line about the motivation for these non rounded test values, so anyone in the future can easily understand such apparently arbitrary choice

**Review by xresende — CHANGES_REQUESTED** [review]
@anacso17 , maybe we should write down a comment line about the motivation for these non rounded test values, so anyone in the future can easily understand such apparently arbitrary choice

**Comment by anacso17** [comment]
> @anacso17 , maybe we should write down a comment line about the motivation for these non rounded test values, so anyone in the future can easily understand such apparently arbitrary choice

@xresende I had left a comment in 169-170 lines:
```
# Test values are slightly different for pstypes that share the same beaglebone.
# This choice helps to identify communication and connection issues.
```
Do you suggest a more detailed comment?

**Comment by xresende** [comment]
> > @anacso17 , maybe we should write down a comment line about the motivation for these non rounded test values, so anyone in the future can easily understand such apparently arbitrary choice
> 
> @xresende I had left a comment in 169-170 lines:
> 
> ```
> # Test values are slightly different for pstypes that share the same beaglebone.
> # This choice helps to identify communication and connection issues.
> ```
> 
> Do you suggest a more detailed comment?

no no. I just did not notice these comment lines, even though I searched for them!

**Review by xresende — APPROVED** [review]

**Pull request merged**
