### PR TITLE
Update rescaling_factor for SI sexts with avg value

### PR DESCRIPTION
**Pull request by xresende**

### CODE REVIEW

**Review by fernandohds564 — CHANGES_REQUESTED** [review]
@xresende, I think we could leave the old rescaling_factors commented  in the files so we can remember their values.

**Comment by xresende** [comment]
> @xresende, I think we could leave the old rescaling_factors commented in the files so we can remember their values.

@fernando, all files already had the original correction factors for all families. if you expand file lines you will see the table.

**Review by fernandohds564 — APPROVED** [review]

**Review by anacso17 — APPROVED** [review]

**Review by murilobalves — APPROVED** [review]

**Comment by xresende** [comment]
@fernandohds564 , @anacso17 , @murilobalves,

should we drop this set of excdata atualization PRs based on re-measurements or merge them ? we should try to decide on this ando not keep it indefinitely. In my opinion we could merge.

**Comment by anacso17** [comment]
> @fernandohds564 , @anacso17 , @murilobalves,
> 
> should we drop this set of excdata atualization PRs based on re-measurements or merge them ? we should try to decide on this ando not keep it indefinitely. In my opinion we could merge.

@xresende I don't remember the details anymore, but I think this PR was tested in the machine and the result was not as expected, so we decided to keep old rescaling factors and did not returned for TS optics studies with rescaling factor variation. In this case, I think we should close this PR.

**Comment by fernandohds564** [comment]
maybe this one we could close, right?

**Comment by anacso17** [comment]
> maybe this one we could close, right?

I agree

**Pull request closed without merging**
