### PR TITLE
New IPs for BO Dip BBBs

### PR DESCRIPTION
**Pull request by pnallin**

### CODE REVIEW

**Comment by gabrielbrunheira** [comment]
I would suggest to keep 10.128.123.105 for B-1 output stages and 10.128.123.106 for B-2 output stages, because these IPs have been related to each of these power supplies all this time, and it feels more natural to me that all Booster family power supplies are in the range of *.101 and *.106. 

Furthermore, because these BBB's are new devices on the net, *.118 for B-1 input stages and *.119 for B-2 input stages looks better to me as well.

**Comment by pnallin** [comment]
The first values I suggested were chosen in order to group input/output stages together.
We can move to yours, @gabrielbrunheira, if it makes it better. No problems!

**Comment by xresende** [comment]
If everyone else agrees, I have no problem with @gabrielbrunheira suggestion.

**Comment by pnallin** [comment]
File updated !

**Comment by gabrielbrunheira** [comment]
I believe https://github.com/lnls-sirius/control-system-constants/pull/187 assigned BO-1 for the output stages and BO-2 for input stages, while this PR made the opposite. I suggest keeping BO-1 (105/106) for output stages and BO-2 (118/119) for input stages.

**Review by xresende — APPROVED** [review]

**Pull request merged**
