### PR TITLE
Update December 2021 schedule

### PR DESCRIPTION
**Pull request by anacso17**
2021 Machine Schedule updates:
- December 16: No longer a scheduled User shift, but a Machine Study shift

### CODE REVIEW

**Review by murilobalves — APPROVED** [review]

**Comment by murilobalves** [comment]
Hi @anacso17. Perhaps a brief text description would make it more explicit what the schedule update is about and it also may help to keep recorded here on github too, what do you think?

**Comment by anacso17** [comment]
Hi @murilobalves! Thanks for your comment!
Do you suggest something like a log file, just like we have in pymodels for lattice changes?
Or just a more descriptive comment on this PR?

**Review by fernandohds564 — APPROVED** [review]

**Comment by murilobalves** [comment]
> Hi @murilobalves! Thanks for your comment! Do you suggest something like a log file, just like we have in pymodels for lattice changes? Or just a more descriptive comment on this PR?

@anacso17 At first, I thought of just a brief description in PR to help us keep up with updates with text descriptions, rather than having to go through the code to understand the actual change. A "versions.txt" file does the job too, with the advantage of concentrating information in one place, but it can get cluttered with information, I don't know... Versions file or updating PRs with short descriptions is up to you, they both sound good to me!

**Comment by anacso17** [comment]
@murilobalves I agree with you that, in some cases like this, a log file can get cluttered. I will try to keep my PRs with more descriptive comments!

**Review by xresende — APPROVED** [review]

**Pull request merged**
