### PR TITLE
Update SI SD excdata

### PR DESCRIPTION
**Pull request by xresende**

### CODE REVIEW

**Review by murilobalves — APPROVED** [review]

**Review by anacso17 — APPROVED** [review]

**Review by fernandohds564 — APPROVED** [review]
@xresende, I know the file `si-sextupole-s15-sd-fam` is not being used any more, but wouldn't be better to update its scaling factor too?

**Review by fernandohds564 — APPROVED** [review]

**Comment by xresende** [comment]
> @xresende, I know the file `si-sextupole-s15-sd-fam` is not being used any more, but wouldn't be better to update its scaling factor too?

with the average rescaling factor along the whole excitation curve? i thought about deleting this file (and the corresponding sf, qf's...)

**Comment by fernandohds564** [comment]
> > @xresende, I know the file `si-sextupole-s15-sd-fam` is not being used any more, but wouldn't be better to update its scaling factor too?
> 
> with the average rescaling factor along the whole excitation curve? i thought about deleting this file (and the corresponding sf, qf's...)

ok! deleting is better than rescaling by the average. It indeed doesn't make sense, since for low current values the errors are large.

**Review by LuanaVilela — APPROVED** [review]

**Comment by xresende** [comment]
@fernandohds564 , see PR https://github.com/lnls-sirius/control-system-constants/pull/217

**Pull request merged**
