### PR TITLE
Excitation Data Rescaling Factor

### PR DESCRIPTION
**Pull request by xresende**
companion PR of https://github.com/lnls-sirius/dev-packages/pull/438 (read description there)

_NOTE_: files in subfolders, like `bo-corrector-ch/bo-corrector-ch-001.txt` are not being used in the control system and therefore had not `rescale_factor` parameter added to them.

**Update 2020-04-13**: rescaling factors based on current accelerator setpoints, as stored in `configdb`, compared to nominal strength values. I used the same rescaling factors of quadrupoles for sextupoles.

```
configdb:	optimize_injector_opt_injbo_high_curr	06/03/2020
pymodel:	SI_V24_04

--- dipoles ---

Fam	    Current-SP  Energy-SP       Energy (model)  Factor
            [A]         [GeV]           [Gev]

B1B2    +394.005077     +02.933370      +03.000000      1.022714

--- quadrupoles ---

Fam	Current-SP      KL-SP           KL (model)      Factor
        [A]             [1/m]           [1/m]

Q2      +149.402408     +00.865549      +00.868066      1.002908
QFB     +139.343437     +01.230943      +01.234522      1.002908
QFP     +139.343437     +01.230943      +01.234522      1.002908
Q4      +134.759026     +00.787846      +00.790137      1.002908
QDB2    +134.324681     -00.477489      -00.478877      1.002908
QDP2    +134.324681     -00.477489      -00.478877      1.002908
QFA     +121.256390     +00.712562      +00.714634      1.002908
Q3      +108.913723     +00.641820      +00.643686      1.002908
Q1      +095.224603     +00.562040      +00.563674      1.002908
QDB1    +078.052446     -00.280132      -00.280947      1.002908
QDP1    +078.052446     -00.280132      -00.280947      1.002908
QDA     +062.962230     -00.226077      -00.226734      1.002908

--- sextupoles ---

Fam	Current-SP      SL-SP           SL (model)      Factor
        [A]             [1/m^2]         [1/m^2]

SFP1    +156.713485     +34.117486      +34.376796      1.007601
SFB1    +155.409769     +33.903705      +34.161390      1.007601
SFP2    +132.789227     +29.543609      +29.768155      1.007601
SFB2    +132.270643     +29.438959      +29.662710      1.007601
SFA1    +127.991673     +28.548396      +28.765378      1.007601
SDP3    +116.809081     -26.157735      -26.126258      0.998797
SDB3    +116.572277     -26.106715      -26.075299      0.998797
SDA1    +109.050500     -24.480469      -24.451010      0.998797
SFA2    +099.905180     +22.441561      +22.612128      1.007601
SDP1    +095.015667     -21.372907      -21.347188      0.998797
SDB1    +094.590203     -21.278702      -21.253097      0.998797
SDA3    +093.406392     -21.016585      -20.991295      0.998797
SDB2    +081.580322     -18.369522      -18.347417      0.998797
SDP2    +081.559501     -18.364842      -18.342742      0.998797
SDA2    +059.294556     -13.348488      -13.332425      0.998797
SDA0    +053.721277     -12.089849      -12.125055      1.002912
SFB0    +049.046545     +11.028898      +11.061015      1.002912
SFP0    +049.046545     +11.028898      +11.061015      1.002912
SDB0    +043.176107     -09.713045      -09.741330      1.002912
SDP0    +043.176107     -09.713045      -09.741330      1.002912
SFA0    +034.975805     +07.862544      +07.885440      1.002912
```

### CODE REVIEW

**Comment by xresende** [comment]
> Some files have an empty line between the other header properties and the units and others don't. Why?
> some files have the rescaling_factor header defined and others don't. Why?

a) In between you starting your review and you writing your comment, I edited the description explaining why I did not bother adding `rescaling_factor` in some (many) files.
b) I think it is an artifact of the github comparison visualization. look at the line numbers!

**Comment by fernandohds564** [comment]
> > Some files have an empty line between the other header properties and the units and others don't. Why?
> > some files have the rescaling_factor header defined and others don't. Why?
> 
> a) I think it is an artifact of the github comparison visualization. look at the line numbers!
> b) In between you starting your review and you writing your comment, I edited the description explaining why I did not bother adding `rescaling_factor` in some (many) files.

b) I think it is better not to make any changes in those files then? don't you think?

**Comment by xresende** [comment]
> > > Some files have an empty line between the other header properties and the units and others don't. Why?
> > > some files have the rescaling_factor header defined and others don't. Why?
> > 
> > 
> > a) I think it is an artifact of the github comparison visualization. look at the line numbers!
> > b) In between you starting your review and you writing your comment, I edited the description explaining why I did not bother adding `rescaling_factor` in some (many) files.
> 
> b) I think it is better not to make any changes in those files then? don't you think?

why? the only change they had was because I ran editor's replace to adjust formatting of <all files> so that parameter values could be aligned in those files that had the new parameter added. the new parameter was added with Ctrl+C/Ctrl+V individually. this is the source of the difference.

**Comment by xresende** [comment]
ok, expanding, so that you can understand my reasoning....

the idea of having files like `bo-corrector-ch/bo-corrector-ch-001.txt`in this repo is that, if we were to use individually measured excitation curves, as some labs use, they would be ready to use. In this case, ideally they should be the same as the ones used for families, including formatting and parameters. I just decided not include de parameters at this point since the use of individual excdata files would require many other changes anyway.

**Comment by xresende** [comment]
> @xresende, have you checked these numbers with the Olog info? or with the configuration values?

I had not. Now I did. Please, read the updated PR description.

**Pull request merged**
